meme ../7.eachpro/hs.CPT.delta.scores.regions.sigdelta.Cytosol.regions.fasta5 -oc ../7.eachpro/meme510Cytosol -seed 123456 -objfun de -neg ../7.eachpro/hs.CPT.delta.scores.regions.sigdelta.background.fasta5 -protein -nmotifs 10 -minw 5 -maxw 10 -p 3 -V
meme ../7.eachpro/hs.CPT.delta.scores.regions.sigdelta.Cytosol.regions.fasta5 -oc ../7.eachpro/meme515Cytosol -seed 123456 -objfun de -neg ../7.eachpro/hs.CPT.delta.scores.regions.sigdelta.background.fasta5 -protein -nmotifs 10 -minw 5 -maxw 15 -p 3 -V
meme ../7.eachpro/hs.CPT.delta.scores.regions.sigdelta.Membrane.regions.fasta5 -oc ../7.eachpro/meme510Membrane -seed 123456 -objfun de -neg ../7.eachpro/hs.CPT.delta.scores.regions.sigdelta.background.fasta5 -protein -nmotifs 10 -minw 5 -maxw 10 -p 3 -V
meme ../7.eachpro/hs.CPT.delta.scores.regions.sigdelta.Membrane.regions.fasta5 -oc ../7.eachpro/meme515Membrane -seed 123456 -objfun de -neg ../7.eachpro/hs.CPT.delta.scores.regions.sigdelta.background.fasta5 -protein -nmotifs 10 -minw 5 -maxw 15 -p 3 -V
meme ../7.eachpro/hs.CPT.delta.scores.regions.sigdelta.Mitochondrion.regions.fasta5 -oc ../7.eachpro/meme510Mitochondrion -seed 123456 -objfun de -neg ../7.eachpro/hs.CPT.delta.scores.regions.sigdelta.background.fasta5 -protein -nmotifs 10 -minw 5 -maxw 10 -p 3 -V
meme ../7.eachpro/hs.CPT.delta.scores.regions.sigdelta.Mitochondrion.regions.fasta5 -oc ../7.eachpro/meme515Mitochondrion -seed 123456 -objfun de -neg ../7.eachpro/hs.CPT.delta.scores.regions.sigdelta.background.fasta5 -protein -nmotifs 10 -minw 5 -maxw 15 -p 3 -V
meme ../7.eachpro/hs.CPT.delta.scores.regions.sigdelta.Secreted.regions.fasta5 -oc ../7.eachpro/meme510Secreted -seed 123456 -objfun de -neg ../7.eachpro/hs.CPT.delta.scores.regions.sigdelta.background.fasta5 -protein -nmotifs 10 -minw 5 -maxw 10 -p 3 -V
meme ../7.eachpro/hs.CPT.delta.scores.regions.sigdelta.Secreted.regions.fasta5 -oc ../7.eachpro/meme515Secreted -seed 123456 -objfun de -neg ../7.eachpro/hs.CPT.delta.scores.regions.sigdelta.background.fasta5 -protein -nmotifs 10 -minw 5 -maxw 15 -p 3 -V

